<#
    Eigenverft.Manifested.Package root module
#>

# Generic ExecutionCore support
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.StandardMessage.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.Stream.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.Json.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.Tar.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.GZip.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.Archive.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.CommandResolution.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.FileSystem.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.ResilientDirectoryTree.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.PathTemplate.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.Registry.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.SystemResources.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.Elevation.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.PathRegistration.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.Npm.ps1"
. "$PSScriptRoot\Support\ExecutionCore\Eigenverft.Manifested.Package.ExecutionCore.InitializeProxyAccessProfile.ps1"

# Package support
. "$PSScriptRoot\Support\ExecutionCore\Upstream\Eigenverft.Manifested.Package.ExecutionCore.Upstream.GitHubRelease.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.ExecutionMessage.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.Bootstrap.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.VersionSelection.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.Config.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.DepotInventory.Management.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.EndpointInventory.Management.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.EndpointAuthoring.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.PublisherInventory.Management.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.Trust.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.DefinitionReference.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.DefinitionSchema.Wire2_0.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.DefinitionSchema.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.DefinitionCatalogValidation.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.LocalEnvironment.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.Selection.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Dependencies.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.DependencyPlan.ps1"
. "$PSScriptRoot\Support\Package\Schema\Eigenverft.Manifested.Package.Package.Source.ps1"
. "$PSScriptRoot\Support\Package\State\Eigenverft.Manifested.Package.Package.Ownership.ps1"
. "$PSScriptRoot\Support\Package\State\Eigenverft.Manifested.Package.Package.OperationHistory.ps1"
. "$PSScriptRoot\Support\Package\State\Eigenverft.Manifested.Package.Package.State.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Readiness.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.Npm.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.PowerShellModule.ps1"
# Package install fragments (order-sensitive); orchestrator last - mirror in TestImports.ps1
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Install.Existing.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Install.Preparation.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Install.Artifact.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Install.InstallerEngine.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Install.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.EntryPoints.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.Shims.ps1"
. "$PSScriptRoot\Support\Package\Execution\Eigenverft.Manifested.Package.Package.PathRegistration.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.AssignmentPlan.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.CommandFlow.ps1"
. "$PSScriptRoot\Support\Package\Lifecycle\Eigenverft.Manifested.Package.Package.Remove.ps1"

# Public commands
. "$PSScriptRoot\Commands\Package\Eigenverft.Manifested.Package.Cmd.GetPackageState.ps1"
. "$PSScriptRoot\Commands\Package\Eigenverft.Manifested.Package.Cmd.GetPackageAssignmentPlan.ps1"
. "$PSScriptRoot\Commands\Package\Eigenverft.Manifested.Package.Cmd.InvokePackage.ps1"
. "$PSScriptRoot\Commands\Package\Eigenverft.Manifested.Package.Cmd.SearchPackage.ps1"
. "$PSScriptRoot\Commands\Depot\Eigenverft.Manifested.Package.Cmd.PackageDepot.ps1"
. "$PSScriptRoot\Commands\Endpoint\Eigenverft.Manifested.Package.Cmd.PackageEndpoint.ps1"
. "$PSScriptRoot\Commands\Publisher\Eigenverft.Manifested.Package.Cmd.PackagePublisher.ps1"
. "$PSScriptRoot\Commands\Trust\Eigenverft.Manifested.Package.Cmd.PackageTrust.ps1"
. "$PSScriptRoot\Commands\Trust\Eigenverft.Manifested.Package.Cmd.PackageCatalogValidation.ps1"
. "$PSScriptRoot\Commands\Web\Eigenverft.Manifested.Package.Cmd.OpenUrlInBrowser.ps1"
. "$PSScriptRoot\Commands\Web\Eigenverft.Manifested.Package.Cmd.OpenPackageDocumentation.ps1"
. "$PSScriptRoot\Commands\Web\Eigenverft.Manifested.Package.Cmd.InvokeWebRequestEx.ps1"
. "$PSScriptRoot\Commands\Module\Eigenverft.Manifested.Package.Cmd.Module.ps1"

# Package definitions
# Package definitions are JSON-only.

